name: test_arrays_binding
version: 0.0.1
description: A web app built using polymer.dart.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  #firebase: '>=0.5.1 <0.6.0'
  firebase:
    path: ../firebase-dart
  dartson: "^0.2.3"
  paper_elements: '>=0.7.0 <0.8.0'
  polymer: '>=0.16.0 <0.17.0'
transformers:
- dartson #has to be before polymer or observables won't work
- polymer:
    entry_points: web/index.html